config/routes.rb
Rails.application.routes.draw do
  root 'static_page#index'
  get 'login', to: 'user_sessions#new', as: :login
  post 'login', to: 'user_sessions#create'
  delete 'logout', to: 'user_sessions#destroy', as: :logout

  resources :users, only: %i[new create]
  resources :books
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
  has_many :books, through: :bbook_authors
end

app/models/book.rb
class Book < ApplicationRecord
  has_one :genre
  has_many :author, through: :book_authors
end

app/models/book_author.rb
class BookAuthor < ApplicationRecord
  belongs_to :book
  belongs_to :author
end

app/models/genre.rb
class Genre < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!

  # validations
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, uniqueness: true, presence: true
  validates :password, length: { minimum: 3 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :require_login

  protect_from_forgery with: :exception

  protected

  def not_authenticated
    redirect_to root_path
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.all
  end

  def show
    @book = Book.find(params[:id])
  end

  def new
    @book = Book.new
  end

  def create
    book = Book.new(book_params)
    book.save
    redirect_to books_path, notice: '本を登録しました。'
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private

  def book_params
    params.require(:book).permit(:title)
  end
end

app/controllers/static_page_controller.rb
class StaticPageController < ApplicationController
  skip_before_action :require_login

  def index
  end
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  skip_before_action :require_login, except: [:destroy]

  def new
    @user = User.new
  end

  def create
    @user = login(params[:email], params[:password])
    
    if @user
      redirect_to root_path
    else
      render :new
    end
  end

  def destroy
    logout
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login

  def index
  end

  def show
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_path, success: 'ユーザー登録が完了しました。'
    else
      flash.now[:danger] = 'ユーザー登録に失敗しました。'
      render :new
    end
  end

  def edit
  end

  def update
  end

  def destroy
  end

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/static_page_helper.rb
module StaticPageHelper
end

app/views/books/edit.html.slim
<h1>Books#edit</h1>
<p>Find me in app/views/books/edit.html.erb</p>

app/views/books/index.html.slim
h1 本の一覧ページ

= link_to '新規登録', new_book_path, class: 'btn btn-primary'

.mb-3
table.table.table-hover
  thead.thead-default
    tr
      th
        | 本の名前
      th
        | 登録日時
  tbody
    - @books.each do |book|
      tr
        td
          = book.title
        td
          = book.created_at

app/views/books/new.html.slim
h1 本の登録ページ

= form_with model: @book, local: true do |f|
  .form-group
    = f.label :title
    = f.text_field :title, class: 'form-control'
  = f.submit '登録', class: 'btn btn-primary'

app/views/books/show.html.slim
h1 本の詳細ページ

app/views/layouts/_footer.html.slim
.footer
  p
    | Copyright ©2020. ぶくまね

app/views/layouts/_header.html.slim
.header
  = link_to root_path do
    span
      = image_tag "bukumane_logo.png", alt: 'ぶくまね'

    / - if logged_in?
      ul
        li
          = link_to root_path do
            span
              | 本棚
        li
          = link_to root_path do
            span
              | ユーザー

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ぶくまね</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%#= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/static_page/index.html.slim
/ タイトル
.top-wrapper.text-center
  tcontainer.top-container
    .row
      .col-md-6.col-md-offset-3
        .title
          h1.text-shadow
            | ぶくまね
      .col-md-8.col-md-offset-2
        p.text-shadow.sub-title
          | あなたの生活をより良くするための読書体験アプリです。
      .col-md-6.col-md-offset-3
        / = link_to "アカウント登録", '/users/new',  class: 'btn btn-arrange btn-block btn-red'
        / = link_to "ログイン", 'sessions/new',      class: 'btn btn-arrange btn-block btn-red'
        p.text-general
          | テストログインはこちらから
	      / = render 'shared/guest_login'

/ サービス紹介
.service-introduction
  .service-title.text-center
    h1.title
      | ぶくまねとは
  .service-all-item
    .item
      .fas.fa-comments
  		  p.explanation
          | ①サービス説明

    .item
      .fas.fa-comments
        p.explanation
          | ②サービス説明

    .item
      .fas.fa-comments
        p.explanation
          | ③サービス説明

  .container
    .row
      .col-md-3
      	.text-center
      	  = link_to('新規ユーザー登録', new_user_path)
      .col-md-3
      	.text-center
      	  = link_to('ログインはこちらから', login_path)
      .col-md-3
      	.text-center
      	  = link_to('ログアウト', logout_path, method: :delete)

app/views/user_sessions/create.html.slim
h1 Sessions#create
p Find me in app/views/sessions/create.html.slim

app/views/user_sessions/new.html.slim
h1 UserSessions#new
= form_tag login_path, method: :post do
  div
    = label_tag 'メールアドレス'
    = text_field_tag :email
  div
    = label_tag 'パスワード'
    = password_field_tag :password
  div
    = label_tag 'パスワード確認用'
    = password_field_tag :password_confirmation
  div
    = submit_tag "ログイン"

app/views/users/edit.html.slim
h1 Users#edit
p Find me in app/views/users/edit.html.slim

app/views/users/index.html.slim
h1 Users#index
p Find me in app/views/users/index.html.slim

app/views/users/new.html.slim
h1 Users#new
= form_for(@user) do |f|
  div
    = f.label 'ファーストネーム'
    = f.text_field :first_name
  div
    = f.label 'ラストネーム'
    = f.text_field :last_name
  div
    = f.label 'メールアドレス'
    = f.text_field :email
  div
    = f.label 'パスワード'
    = f.password_field :password
  div
    = f.label 'パスワード確認用'
    = f.password_field :password_confirmation
  div
    = f.submit '登録'

app/views/users/show.html.slim
h1 Users#show
p Find me in app/views/users/show.html.slim